kafka:
  bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
  topic:
    twiter-feed-topic: twiter-feed-topic
twitter:
  consumer-key: o9hooByWxpk5qCbO9XBq4RDbn
  consumer-secret: kGvO6h59R6cquTi5ntsyAvpJU75EixJNQSZqDDIpCRdXILR12s
  access-token: 86658823-dZRwKmjJJNyzlzzucDJfGbofKsc3r4gphnCiIIndv
  consumer-token-secret: V07QFo23A8mTrHZUZmGIJUK0Rz495rZBAG41JT2x2XxG7      