kafka:
  bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
  topic:
    twiter-feed-topic: twiter-feed-topic
twitter:
  consumer-key:  
  consumer-secret:  
  access-token:  
  access-secret-token:  
spark:
  home: E:/software/apachespark/spark
  master.uri: local
  app.name: twiter-feed        